# Generated by Django 5.2.7 on 2026-05-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Bo'lim"),
        ),
    ]
