# Generated by Django 5.2.7 on 2026-05-17 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('icon', models.CharField(default='Zap', max_length=100, verbose_name='Icon nomi')),
                ('color', models.CharField(default='emerald', max_length=50, verbose_name='Rangi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xususiyat',
                'verbose_name_plural': 'Xususiyatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='features/', verbose_name='Rasm')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtitr')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('users_stat', models.CharField(default='20k+', max_length=50, verbose_name='Faol foydalanuvchilar soni')),
                ('rating_stat', models.CharField(default='4.8', max_length=50, verbose_name='Reyting')),
                ('tasks_stat', models.CharField(default='Faol', max_length=50, verbose_name='Vazifa/Level')),
                ('step1_title', models.CharField(max_length=100, verbose_name='Qadam 1 Nomi')),
                ('step1_desc', models.CharField(max_length=255, verbose_name='Qadam 1 Tavsifi')),
                ('step2_title', models.CharField(max_length=100, verbose_name='Qadam 2 Nomi')),
                ('step2_desc', models.CharField(max_length=255, verbose_name='Qadam 2 Tavsifi')),
                ('step3_title', models.CharField(max_length=100, verbose_name='Qadam 3 Nomi')),
                ('step3_desc', models.CharField(max_length=255, verbose_name='Qadam 3 Tavsifi')),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='ads.feature', verbose_name='Xususiyat')),
            ],
            options={
                'verbose_name': 'Xususiyat Tafsiloti',
                'verbose_name_plural': 'Xususiyat Tafsilotlari',
            },
        ),
    ]
