# Generated by Django 6.0.5 on 2026-05-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_feature_featuredetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Tavsif (Batafsil)')),
                ('category', models.CharField(max_length=100, verbose_name="Yo'nalish")),
                ('image', models.ImageField(upload_to='blogs/', verbose_name='Asosiy Rasm')),
                ('author', models.CharField(max_length=150, verbose_name='Muallif ismi')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Muallif Rasmi')),
                ('hashtags', models.CharField(blank=True, max_length=250, null=True, verbose_name='Heshteglar')),
                ('read_time', models.CharField(default='5 min', max_length=50, verbose_name="O'qish vaqti")),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr qilingan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Yangilik va Blog',
                'verbose_name_plural': 'Yangiliklar va Bloglar',
                'ordering': ['-created_at'],
            },
        ),
    ]
