# Generated by Django 5.2.7 on 2026-05-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': "Ko'p beriladigan savol",
                'verbose_name_plural': "Ko'p beriladigan savollar",
                'ordering': ['order_index', '-created_at'],
            },
        ),
    ]
