# Generated by Django 5.2.7 on 2026-05-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=254, verbose_name='Email yoki Telefon'),
        ),
    ]
